server:
  port: 8090
spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://bk_test@rm-bp1095tso1hk1047k.mysql.rds.aliyuncs.com:3306/test_demo
      username: user
      password: zhutao2713
    db2:
      jdbc-url: jdbc:mysql://bk_test@rm-bp1095tso1hk1047k.mysql.rds.aliyuncs.com:3306/bk_test
      username: user
      password: zhutao2713